### ISSUE TITLE
大神你好，终于找到了你，非常希望能查看你的Android同屏方案源码，这对我非常重要！谢谢。

### ISSUE THREAD

**Issue by luddite1989** [ele828/blog#2]
大神你好，昨天看到了你写的《Android同屏直播方案》这篇文章，对我的启发特别大，你用到的技术解决了我长期的困惑和难题。所以，非常需要你的这份源码，希望有时间能够学习一下。请大神开源，或传我一份吧，万分跪谢。我相信，站在大神你的肩膀上，能让我越走越远！谢谢，谢谢！我的qq：362673301，希望大神您能够看见我的渴望！

**Comment by ele828** [comment]
不好意思，这个项目不是开源的无法分享源码。
